application: benlaupedia
version: 4
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /media
  static_dir: _generated_media

- url: /.*
  script: common/appenginepatch/main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^\.git/.*

